(define (domain Blocks)
(:constants
  A D B C - object)
(:predicates
  (onblock ?x ?y - object)
  (on ?x ?y - object)
  (block ?x - object)
  (blocked ?x - object)
  (updating)
  (incompatible_update)
  (ins_onblock ?x ?y - object)
  (del_onblock ?x ?y - object)
  (Ap_onblock ?x ?y - object)
  (Am_onblock ?x ?y - object)
  (InsCl_onblock ?x ?y - object)
  (inv_onblock ?x0 ?x1 - object)
  (ins_inv_onblock ?x0 ?x1 - object)
  (del_inv_onblock ?x0 ?x1 - object)
  (Ap_inv_onblock ?x0 ?x1 - object)
  (Am_inv_onblock ?x0 ?x1 - object)
  (InsCl_inv_onblock ?x0 ?x1 - object)
  (exists_onblock ?x0 - object)
  (ins_exists_onblock ?x0 - object)
  (del_exists_onblock ?x0 - object)
  (Ap_exists_onblock ?x0 - object)
  (Am_exists_onblock ?x0 - object)
  (InsCl_exists_onblock ?x0 - object)
  (exists_inv_onblock ?x0 - object)
  (ins_exists_inv_onblock ?x0 - object)
  (del_exists_inv_onblock ?x0 - object)
  (Ap_exists_inv_onblock ?x0 - object)
  (Am_exists_inv_onblock ?x0 - object)
  (InsCl_exists_inv_onblock ?x0 - object)
  (ins_on ?x ?y - object)
  (del_on ?x ?y - object)
  (Ap_on ?x ?y - object)
  (Am_on ?x ?y - object)
  (InsCl_on ?x ?y - object)
  (inv_on ?x0 ?x1 - object)
  (ins_inv_on ?x0 ?x1 - object)
  (del_inv_on ?x0 ?x1 - object)
  (Ap_inv_on ?x0 ?x1 - object)
  (Am_inv_on ?x0 ?x1 - object)
  (InsCl_inv_on ?x0 ?x1 - object)
  (exists_on ?x0 - object)
  (ins_exists_on ?x0 - object)
  (del_exists_on ?x0 - object)
  (Ap_exists_on ?x0 - object)
  (Am_exists_on ?x0 - object)
  (InsCl_exists_on ?x0 - object)
  (exists_inv_on ?x0 - object)
  (ins_exists_inv_on ?x0 - object)
  (del_exists_inv_on ?x0 - object)
  (Ap_exists_inv_on ?x0 - object)
  (Am_exists_inv_on ?x0 - object)
  (InsCl_exists_inv_on ?x0 - object)
  (ins_block ?x - object)
  (del_block ?x - object)
  (Ap_block ?x - object)
  (Am_block ?x - object)
  (InsCl_block ?x - object)
  (ins_blocked ?x - object)
  (del_blocked ?x - object)
  (Ap_blocked ?x - object)
  (Am_blocked ?x - object)
  (InsCl_blocked ?x - object)
  (AOrApCl_exists_onblock ?x0 - object)
  (ApCl_block ?x0 - object)
  (AOrApCl_exists_on ?x0 - object)
  (ApCl_inv_on ?x0 ?x1 - object)
  (DelCl_on ?x0 ?x1 - object)
  (ApCl_inv_onblock ?x0 ?x1 - object)
  (DelCl_onblock ?x0 ?x1 - object)
  (ApCl_on ?x0 ?x1 - object)
  (PreInsCl_exists_onblock_sub_exists_on ?x0 - object)
  (AOrApCl_on ?x0 ?x1 - object)
  (DelCl_exists_on ?x0 - object)
  (AOrApCl_inv_on ?x0 ?x1 - object)
  (DelCl_inv_onblock ?x0 ?x1 - object)
  (ApCl_exists_onblock ?x0 - object)
  (PreInsCl_exists_inv_onblock_sub_block ?x0 - object)
  (AOrApCl_inv_onblock ?x0 ?x1 - object)
  (DelCl_exists_onblock ?x0 - object)
  (AOrApCl_onblock ?x0 ?x1 - object)
  (DATALOG_BLOCKED ?x0 - object)
  (ApCl_onblock ?x0 ?x1 - object)
  (DelCl_block ?x0 - object)
  (AOrApCl_exists_inv_onblock ?x0 - object)
  (AOrApCl_block ?x0 - object)
  (AOrApCl_exists_inv_on ?x0 - object)
  (AOrApCl_blocked ?x0 - object)
  (DelCl_inv_on ?x0 ?x1 - object)
  (PreInsCl_onblock_sub_on ?x0 ?x1 - object)
  (DelCl_exists_inv_onblock ?x0 - object)
  (ApCl_blocked ?x0 - object)
  (ApCl_exists_on ?x0 - object)
  (DelCl_exists_inv_on ?x0 - object)
  (Min_onblock_in_onblock_sub_on ?x0 ?x1 - object)
  (PreInsCl_exists_inv_onblock_sub_exists_inv_on ?x0 - object)
  (PreInsCl_inv_onblock_sub_inv_on ?x0 ?x1 - object)
  (ApCl_exists_inv_on ?x0 - object)
  (Min_exists_inv_onblock_in_exists_inv_onblock_sub_block ?x0 - object)
  (ApCl_exists_inv_onblock ?x0 - object)
  (Min_exists_onblock_in_exists_onblock_sub_exists_on ?x0 - object)
  (Min_exists_inv_onblock_in_exists_inv_onblock_sub_exists_inv_on ?x0 - object)
  (DATALOG_BLOCK ?x0 - object)
  (DelCl_blocked ?x0 - object)
  (DATALOG_ON ?x0 ?x1 - object)
  (Min_inv_onblock_in_inv_onblock_sub_inv_on ?x0 ?x1 - object)
  (PreInsCl_exists_inv_on_sub_blocked ?x0 - object)
  (Min_exists_inv_on_in_exists_inv_on_sub_blocked ?x0 - object))
(:derived (AOrApCl_exists_onblock ?x0 - object)
          (exists_onblock ?x0))
(:derived (InsCl_blocked ?x0 - object)
          (and (DelCl_exists_inv_on ?x0) (PreInsCl_exists_inv_on_sub_blocked ?x0)))
(:derived (del_onblock ?x0 ?x1 - object)
          (and (DelCl_onblock ?x0 ?x1) (onblock ?x0 ?x1)))
(:derived (ins_blocked ?x0 - object)
          (and (InsCl_blocked ?x0) (not (blocked ?x0))))
(:derived (ApCl_block ?x0 - object)
          (ApCl_exists_inv_onblock ?x0))
(:derived (AOrApCl_exists_on ?x0 - object)
          (AOrApCl_exists_onblock ?x0))
(:derived (del_exists_on ?x0 - object)
          (and (DelCl_exists_on ?x0) (exists_on ?x0)))
(:derived (ApCl_inv_on ?x0 ?x1 - object)
          (ApCl_inv_onblock ?x0 ?x1))
(:derived (DelCl_on ?x0 ?x1 - object)
          (and (AOrApCl_on ?x0 ?x1) (DelCl_exists_on ?x0)))
(:derived (ins_inv_on ?x0 ?x1 - object)
          (and (Ap_inv_on ?x0 ?x1) (not (inv_on ?x0 ?x1))))
(:derived (updating )
          (exists (?y0 - object) (Am_blocked ?y0)))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Ap_inv_onblock ?y0 ?y1)))
(:derived (ApCl_inv_onblock ?x0 ?x1 - object)
          (Ap_inv_onblock ?x0 ?x1))
(:derived (InsCl_exists_inv_on ?x0 - object)
          (and (DelCl_exists_inv_onblock ?x0) (PreInsCl_exists_inv_onblock_sub_exists_inv_on ?x0)))
(:derived (DelCl_onblock ?x0 ?x1 - object)
          (and (DelCl_on ?x0 ?x1) (Min_onblock_in_onblock_sub_on ?x0 ?x1)))
(:derived (ins_exists_on ?x0 - object)
          (and (InsCl_exists_on ?x0) (not (exists_on ?x0))))
(:derived (ApCl_on ?x0 ?x1 - object)
          (Ap_on ?x0 ?x1))
(:derived (PreInsCl_exists_onblock_sub_exists_on ?x0 - object)
          (and (AOrApCl_exists_onblock ?x0) (not (DelCl_exists_on ?x0))))
(:derived (AOrApCl_on ?x0 ?x1 - object)
          (on ?x0 ?x1))
(:derived (DelCl_exists_on ?x0 - object)
          (Am_exists_on ?x0))
(:derived (DelCl_on ?x0 ?x1 - object)
          (Am_on ?x0 ?x1))
(:derived (AOrApCl_inv_on ?x0 ?x1 - object)
          (inv_on ?x0 ?x1))
(:derived (DelCl_inv_onblock ?x0 ?x1 - object)
          (and (AOrApCl_inv_onblock ?x0 ?x1) (DelCl_exists_inv_onblock ?x0)))
(:derived (ApCl_exists_onblock ?x0 - object)
          (Ap_exists_onblock ?x0))
(:derived (DelCl_inv_onblock ?x0 ?x1 - object)
          (Am_inv_onblock ?x0 ?x1))
(:derived (InsCl_exists_onblock ?x0 - object)
          (exists (?y0 - object) (and (AOrApCl_onblock ?x0 ?y0) (DelCl_onblock ?x0 ?y0) (not (DelCl_exists_onblock ?x0)))))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (Am_onblock ?y0 ?y1) (ApCl_onblock ?y0 ?y1))))
(:derived (PreInsCl_exists_inv_onblock_sub_block ?x0 - object)
          (and (AOrApCl_exists_inv_onblock ?x0) (not (DelCl_block ?x0))))
(:derived (AOrApCl_inv_onblock ?x0 ?x1 - object)
          (AOrApCl_onblock ?x1 ?x0))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Ap_on ?y0 ?y1)))
(:derived (DelCl_exists_onblock ?x0 - object)
          (Am_exists_onblock ?x0))
(:derived (del_blocked ?x0 - object)
          (and (DelCl_blocked ?x0) (blocked ?x0)))
(:derived (ins_exists_inv_onblock ?x0 - object)
          (and (Ap_exists_inv_onblock ?x0) (not (exists_inv_onblock ?x0))))
(:derived (AOrApCl_inv_on ?x0 ?x1 - object)
          (AOrApCl_on ?x1 ?x0))
(:derived (AOrApCl_onblock ?x0 ?x1 - object)
          (onblock ?x0 ?x1))
(:derived (AOrApCl_exists_onblock ?x0 - object)
          (exists (?y0 - object) (AOrApCl_onblock ?x0 ?y0)))
(:derived (del_inv_onblock ?x0 ?x1 - object)
          (and (DelCl_inv_onblock ?x0 ?x1) (inv_onblock ?x0 ?x1)))
(:derived (del_on ?x0 ?x1 - object)
          (and (DelCl_on ?x0 ?x1) (on ?x0 ?x1)))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Ap_onblock ?y0 ?y1)))
(:derived (ins_on ?x0 ?x1 - object)
          (and (InsCl_on ?x0 ?x1) (not (on ?x0 ?x1))))
(:derived (ins_inv_onblock ?x0 ?x1 - object)
          (and (InsCl_inv_onblock ?x0 ?x1) (not (inv_onblock ?x0 ?x1))))
(:derived (DATALOG_BLOCKED ?x0 - object)
          (blocked ?x0))
(:derived (DATALOG_BLOCKED ?x0 - object)
          (exists (?y0 - object) (DATALOG_ON ?y0 ?x0)))
(:derived (ApCl_onblock ?x0 ?x1 - object)
          (Ap_onblock ?x0 ?x1))
(:derived (DelCl_block ?x0 - object)
          (Am_block ?x0))
(:derived (AOrApCl_exists_inv_onblock ?x0 - object)
          (exists (?y0 - object) (AOrApCl_inv_onblock ?x0 ?y0)))
(:derived (AOrApCl_block ?x0 - object)
          (Ap_block ?x0))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Ap_inv_on ?y0 ?y1)))
(:derived (updating )
          (exists (?y0 - object) (Ap_exists_inv_on ?y0)))
(:derived (AOrApCl_exists_inv_onblock ?x0 - object)
          (Ap_exists_inv_onblock ?x0))
(:derived (ApCl_onblock ?x0 ?x1 - object)
          (ApCl_inv_onblock ?x1 ?x0))
(:derived (AOrApCl_exists_inv_on ?x0 - object)
          (AOrApCl_exists_inv_onblock ?x0))
(:derived (ins_block ?x0 - object)
          (and (InsCl_block ?x0) (not (block ?x0))))
(:derived (updating )
          (exists (?y0 - object) (Am_block ?y0)))
(:derived (ins_exists_inv_on ?x0 - object)
          (and (InsCl_exists_inv_on ?x0) (not (exists_inv_on ?x0))))
(:derived (AOrApCl_blocked ?x0 - object)
          (Ap_blocked ?x0))
(:derived (ins_exists_inv_onblock ?x0 - object)
          (and (InsCl_exists_inv_onblock ?x0) (not (exists_inv_onblock ?x0))))
(:derived (ins_block ?x0 - object)
          (and (Ap_block ?x0) (not (block ?x0))))
(:derived (updating )
          (exists (?y0 - object) (Am_exists_inv_on ?y0)))
(:derived (DelCl_inv_on ?x0 ?x1 - object)
          (Am_inv_on ?x0 ?x1))
(:derived (PreInsCl_onblock_sub_on ?x0 ?x1 - object)
          (and (AOrApCl_onblock ?x0 ?x1) (not (DelCl_on ?x0 ?x1))))
(:derived (DelCl_exists_inv_onblock ?x0 - object)
          (and (DelCl_block ?x0) (Min_exists_inv_onblock_in_exists_inv_onblock_sub_block ?x0)))
(:derived (AOrApCl_onblock ?x0 ?x1 - object)
          (Ap_onblock ?x0 ?x1))
(:derived (ApCl_blocked ?x0 - object)
          (ApCl_exists_inv_on ?x0))
(:derived (ins_exists_onblock ?x0 - object)
          (and (Ap_exists_onblock ?x0) (not (exists_onblock ?x0))))
(:derived (ApCl_on ?x0 ?x1 - object)
          (ApCl_inv_on ?x1 ?x0))
(:derived (ins_inv_onblock ?x0 ?x1 - object)
          (and (Ap_inv_onblock ?x0 ?x1) (not (inv_onblock ?x0 ?x1))))
(:derived (updating )
          (exists (?y0 - object) (Am_exists_on ?y0)))
(:derived (ApCl_block ?x0 - object)
          (Ap_block ?x0))
(:derived (AOrApCl_inv_on ?x0 ?x1 - object)
          (AOrApCl_inv_onblock ?x0 ?x1))
(:derived (InsCl_exists_on ?x0 - object)
          (exists (?y0 - object) (and (AOrApCl_on ?x0 ?y0) (DelCl_on ?x0 ?y0) (not (DelCl_exists_on ?x0)))))
(:derived (InsCl_exists_inv_on ?x0 - object)
          (exists (?y0 - object) (and (AOrApCl_inv_on ?x0 ?y0) (DelCl_inv_on ?x0 ?y0) (not (DelCl_exists_inv_on ?x0)))))
(:derived (InsCl_block ?x0 - object)
          (and (DelCl_exists_inv_onblock ?x0) (PreInsCl_exists_inv_onblock_sub_block ?x0)))
(:derived (ins_on ?x0 ?x1 - object)
          (and (Ap_on ?x0 ?x1) (not (on ?x0 ?x1))))
(:derived (DelCl_inv_on ?x0 ?x1 - object)
          (DelCl_on ?x1 ?x0))
(:derived (ins_inv_on ?x0 ?x1 - object)
          (and (InsCl_inv_on ?x0 ?x1) (not (inv_on ?x0 ?x1))))
(:derived (AOrApCl_on ?x0 ?x1 - object)
          (AOrApCl_onblock ?x0 ?x1))
(:derived (ApCl_exists_on ?x0 - object)
          (Ap_exists_on ?x0))
(:derived (AOrApCl_on ?x0 ?x1 - object)
          (AOrApCl_inv_on ?x1 ?x0))
(:derived (DelCl_exists_inv_on ?x0 - object)
          (Am_exists_inv_on ?x0))
(:derived (Min_onblock_in_onblock_sub_on ?x0 ?x1 - object)
          (and (AOrApCl_onblock ?x0 ?x1) (not (ApCl_onblock ?x0 ?x1))))
(:derived (PreInsCl_exists_inv_onblock_sub_exists_inv_on ?x0 - object)
          (and (AOrApCl_exists_inv_onblock ?x0) (not (DelCl_exists_inv_on ?x0))))
(:derived (updating )
          (exists (?y0 - object) (Ap_block ?y0)))
(:derived (DelCl_inv_on ?x0 ?x1 - object)
          (and (AOrApCl_inv_on ?x0 ?x1) (DelCl_exists_inv_on ?x0)))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Am_onblock ?y0 ?y1)))
(:derived (ApCl_inv_on ?x0 ?x1 - object)
          (Ap_inv_on ?x0 ?x1))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Am_inv_on ?y0 ?y1)))
(:derived (DelCl_inv_onblock ?x0 ?x1 - object)
          (and (DelCl_inv_on ?x0 ?x1) (Min_inv_onblock_in_inv_onblock_sub_inv_on ?x0 ?x1)))
(:derived (DelCl_on ?x0 ?x1 - object)
          (DelCl_inv_on ?x1 ?x0))
(:derived (DelCl_exists_inv_onblock ?x0 - object)
          (and (DelCl_exists_inv_on ?x0) (Min_exists_inv_onblock_in_exists_inv_onblock_sub_exists_inv_on ?x0)))
(:derived (PreInsCl_inv_onblock_sub_inv_on ?x0 ?x1 - object)
          (and (AOrApCl_inv_onblock ?x0 ?x1) (not (DelCl_inv_on ?x0 ?x1))))
(:derived (AOrApCl_onblock ?x0 ?x1 - object)
          (AOrApCl_inv_onblock ?x1 ?x0))
(:derived (AOrApCl_inv_onblock ?x0 ?x1 - object)
          (inv_onblock ?x0 ?x1))
(:derived (ApCl_exists_inv_on ?x0 - object)
          (exists (?y0 - object) (ApCl_inv_on ?x0 ?y0)))
(:derived (updating )
          (exists (?y0 - object) (Ap_exists_on ?y0)))
(:derived (AOrApCl_on ?x0 ?x1 - object)
          (Ap_on ?x0 ?x1))
(:derived (Min_exists_inv_onblock_in_exists_inv_onblock_sub_block ?x0 - object)
          (and (AOrApCl_exists_inv_onblock ?x0) (not (ApCl_exists_inv_onblock ?x0))))
(:derived (AOrApCl_inv_onblock ?x0 ?x1 - object)
          (Ap_inv_onblock ?x0 ?x1))
(:derived (ApCl_exists_inv_onblock ?x0 - object)
          (exists (?y0 - object) (ApCl_inv_onblock ?x0 ?y0)))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (Am_inv_on ?y0 ?y1) (ApCl_inv_on ?y0 ?y1))))
(:derived (ins_exists_on ?x0 - object)
          (and (Ap_exists_on ?x0) (not (exists_on ?x0))))
(:derived (Min_exists_onblock_in_exists_onblock_sub_exists_on ?x0 - object)
          (and (AOrApCl_exists_onblock ?x0) (not (ApCl_exists_onblock ?x0))))
(:derived (ins_blocked ?x0 - object)
          (and (Ap_blocked ?x0) (not (blocked ?x0))))
(:derived (ApCl_exists_inv_on ?x0 - object)
          (Ap_exists_inv_on ?x0))
(:derived (updating )
          (exists (?y0 - object) (Ap_blocked ?y0)))
(:derived (updating )
          (exists (?y0 - object) (Am_exists_onblock ?y0)))
(:derived (ApCl_on ?x0 ?x1 - object)
          (ApCl_onblock ?x0 ?x1))
(:derived (DelCl_onblock ?x0 ?x1 - object)
          (Am_onblock ?x0 ?x1))
(:derived (del_exists_inv_on ?x0 - object)
          (and (DelCl_exists_inv_on ?x0) (exists_inv_on ?x0)))
(:derived (AOrApCl_exists_onblock ?x0 - object)
          (Ap_exists_onblock ?x0))
(:derived (InsCl_exists_inv_onblock ?x0 - object)
          (exists (?y0 - object) (and (AOrApCl_inv_onblock ?x0 ?y0) (DelCl_inv_onblock ?x0 ?y0) (not (DelCl_exists_inv_onblock ?x0)))))
(:derived (updating )
          (exists (?y0 - object) (Ap_exists_onblock ?y0)))
(:derived (ins_exists_onblock ?x0 - object)
          (and (InsCl_exists_onblock ?x0) (not (exists_onblock ?x0))))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_exists_on ?y0) (ApCl_exists_on ?y0))))
(:derived (AOrApCl_exists_on ?x0 - object)
          (exists (?y0 - object) (AOrApCl_on ?x0 ?y0)))
(:derived (del_block ?x0 - object)
          (and (DelCl_block ?x0) (block ?x0)))
(:derived (InsCl_on ?x0 ?x1 - object)
          (and (DelCl_onblock ?x0 ?x1) (PreInsCl_onblock_sub_on ?x0 ?x1)))
(:derived (Min_exists_inv_onblock_in_exists_inv_onblock_sub_exists_inv_on ?x0 - object)
          (and (AOrApCl_exists_inv_onblock ?x0) (not (ApCl_exists_inv_onblock ?x0))))
(:derived (InsCl_inv_on ?x0 ?x1 - object)
          (and (DelCl_inv_onblock ?x0 ?x1) (PreInsCl_inv_onblock_sub_inv_on ?x0 ?x1)))
(:derived (del_exists_onblock ?x0 - object)
          (and (DelCl_exists_onblock ?x0) (exists_onblock ?x0)))
(:derived (ApCl_blocked ?x0 - object)
          (Ap_blocked ?x0))
(:derived (ApCl_exists_on ?x0 - object)
          (exists (?y0 - object) (ApCl_on ?x0 ?y0)))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_exists_inv_onblock ?y0) (ApCl_exists_inv_onblock ?y0))))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Am_inv_onblock ?y0 ?y1)))
(:derived (DATALOG_BLOCK ?x0 - object)
          (block ?x0))
(:derived (DATALOG_BLOCK ?x0 - object)
          (exists (?y0 - object) (onblock ?y0 ?x0)))
(:derived (DelCl_exists_onblock ?x0 - object)
          (and (DelCl_exists_on ?x0) (Min_exists_onblock_in_exists_onblock_sub_exists_on ?x0)))
(:derived (AOrApCl_blocked ?x0 - object)
          (AOrApCl_exists_inv_on ?x0))
(:derived (updating )
          (exists (?y0 - object) (Ap_exists_inv_onblock ?y0)))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_blocked ?y0) (ApCl_blocked ?y0))))
(:derived (ins_onblock ?x0 ?x1 - object)
          (and (InsCl_onblock ?x0 ?x1) (not (onblock ?x0 ?x1))))
(:derived (updating )
          (exists (?y0 ?y1 - object) (Am_on ?y0 ?y1)))
(:derived (DelCl_exists_inv_onblock ?x0 - object)
          (Am_exists_inv_onblock ?x0))
(:derived (DelCl_blocked ?x0 - object)
          (Am_blocked ?x0))
(:derived (DelCl_onblock ?x0 ?x1 - object)
          (DelCl_inv_onblock ?x1 ?x0))
(:derived (AOrApCl_blocked ?x0 - object)
          (blocked ?x0))
(:derived (DATALOG_ON ?x0 ?x1 - object)
          (on ?x0 ?x1))
(:derived (DATALOG_ON ?x0 ?x1 - object)
          (onblock ?x0 ?x1))
(:derived (AOrApCl_block ?x0 - object)
          (AOrApCl_exists_inv_onblock ?x0))
(:derived (ApCl_exists_inv_onblock ?x0 - object)
          (Ap_exists_inv_onblock ?x0))
(:derived (Min_inv_onblock_in_inv_onblock_sub_inv_on ?x0 ?x1 - object)
          (and (AOrApCl_inv_onblock ?x0 ?x1) (not (ApCl_inv_onblock ?x0 ?x1))))
(:derived (ins_exists_inv_on ?x0 - object)
          (and (Ap_exists_inv_on ?x0) (not (exists_inv_on ?x0))))
(:derived (AOrApCl_exists_on ?x0 - object)
          (Ap_exists_on ?x0))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (Am_on ?y0 ?y1) (ApCl_on ?y0 ?y1))))
(:derived (AOrApCl_exists_inv_on ?x0 - object)
          (Ap_exists_inv_on ?x0))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_exists_inv_on ?y0) (ApCl_exists_inv_on ?y0))))
(:derived (updating )
          (exists (?y0 - object) (Am_exists_inv_onblock ?y0)))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_block ?y0) (ApCl_block ?y0))))
(:derived (AOrApCl_block ?x0 - object)
          (block ?x0))
(:derived (AOrApCl_exists_inv_on ?x0 - object)
          (exists (?y0 - object) (AOrApCl_inv_on ?x0 ?y0)))
(:derived (PreInsCl_exists_inv_on_sub_blocked ?x0 - object)
          (and (AOrApCl_exists_inv_on ?x0) (not (DelCl_blocked ?x0))))
(:derived (AOrApCl_exists_on ?x0 - object)
          (exists_on ?x0))
(:derived (ApCl_inv_onblock ?x0 ?x1 - object)
          (ApCl_onblock ?x1 ?x0))
(:derived (Min_exists_inv_on_in_exists_inv_on_sub_blocked ?x0 - object)
          (and (AOrApCl_exists_inv_on ?x0) (not (ApCl_exists_inv_on ?x0))))
(:derived (del_inv_on ?x0 ?x1 - object)
          (and (DelCl_inv_on ?x0 ?x1) (inv_on ?x0 ?x1)))
(:derived (ApCl_exists_on ?x0 - object)
          (ApCl_exists_onblock ?x0))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (Am_exists_onblock ?y0) (ApCl_exists_onblock ?y0))))
(:derived (AOrApCl_inv_on ?x0 ?x1 - object)
          (Ap_inv_on ?x0 ?x1))
(:derived (ApCl_exists_onblock ?x0 - object)
          (exists (?y0 - object) (ApCl_onblock ?x0 ?y0)))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (Am_inv_onblock ?y0 ?y1) (ApCl_inv_onblock ?y0 ?y1))))
(:derived (DelCl_inv_onblock ?x0 ?x1 - object)
          (DelCl_onblock ?x1 ?x0))
(:derived (ApCl_inv_on ?x0 ?x1 - object)
          (ApCl_on ?x1 ?x0))
(:derived (ApCl_exists_inv_on ?x0 - object)
          (ApCl_exists_inv_onblock ?x0))
(:derived (InsCl_exists_on ?x0 - object)
          (and (DelCl_exists_onblock ?x0) (PreInsCl_exists_onblock_sub_exists_on ?x0)))
(:derived (ins_onblock ?x0 ?x1 - object)
          (and (Ap_onblock ?x0 ?x1) (not (onblock ?x0 ?x1))))
(:derived (DelCl_onblock ?x0 ?x1 - object)
          (and (AOrApCl_onblock ?x0 ?x1) (DelCl_exists_onblock ?x0)))
(:derived (AOrApCl_exists_inv_on ?x0 - object)
          (exists_inv_on ?x0))
(:derived (DelCl_exists_inv_on ?x0 - object)
          (and (DelCl_blocked ?x0) (Min_exists_inv_on_in_exists_inv_on_sub_blocked ?x0)))
(:derived (AOrApCl_exists_inv_onblock ?x0 - object)
          (exists_inv_onblock ?x0))
(:derived (del_exists_inv_onblock ?x0 - object)
          (and (DelCl_exists_inv_onblock ?x0) (exists_inv_onblock ?x0)))
(:action move
  :parameters (?x ?y ?z - object)
  :precondition (and (DATALOG_ON ?x ?y) (not (DATALOG_BLOCKED ?x)) (not (DATALOG_BLOCKED ?z)) (not (updating)))
  :effect (and (Am_on ?x ?y) (Ap_onblock ?x ?z)))
(:action update
  :parameters ()
  :precondition (and (updating) (not (incompatible_update)))
  :effect (and (forall (?x ?y) (when (ins_onblock ?x ?y) (onblock ?x ?y))) (forall (?x ?y) (when (del_onblock ?x ?y) (not (onblock ?x ?y)))) (forall (?x ?y) (when (Ap_onblock ?x ?y) (not (Ap_onblock ?x ?y)))) (forall (?x ?y) (when (Am_onblock ?x ?y) (not (Am_onblock ?x ?y)))) (forall (?x0 ?x1) (when (ins_inv_onblock ?x0 ?x1) (inv_onblock ?x0 ?x1))) (forall (?x0 ?x1) (when (del_inv_onblock ?x0 ?x1) (not (inv_onblock ?x0 ?x1)))) (forall (?x0 ?x1) (when (Ap_inv_onblock ?x0 ?x1) (not (Ap_inv_onblock ?x0 ?x1)))) (forall (?x0 ?x1) (when (Am_inv_onblock ?x0 ?x1) (not (Am_inv_onblock ?x0 ?x1)))) (forall (?x0) (when (ins_exists_onblock ?x0) (exists_onblock ?x0))) (forall (?x0) (when (del_exists_onblock ?x0) (not (exists_onblock ?x0)))) (forall (?x0) (when (Ap_exists_onblock ?x0) (not (Ap_exists_onblock ?x0)))) (forall (?x0) (when (Am_exists_onblock ?x0) (not (Am_exists_onblock ?x0)))) (forall (?x0) (when (ins_exists_inv_onblock ?x0) (exists_inv_onblock ?x0))) (forall (?x0) (when (del_exists_inv_onblock ?x0) (not (exists_inv_onblock ?x0)))) (forall (?x0) (when (Ap_exists_inv_onblock ?x0) (not (Ap_exists_inv_onblock ?x0)))) (forall (?x0) (when (Am_exists_inv_onblock ?x0) (not (Am_exists_inv_onblock ?x0)))) (forall (?x ?y) (when (ins_on ?x ?y) (on ?x ?y))) (forall (?x ?y) (when (del_on ?x ?y) (not (on ?x ?y)))) (forall (?x ?y) (when (Ap_on ?x ?y) (not (Ap_on ?x ?y)))) (forall (?x ?y) (when (Am_on ?x ?y) (not (Am_on ?x ?y)))) (forall (?x0 ?x1) (when (ins_inv_on ?x0 ?x1) (inv_on ?x0 ?x1))) (forall (?x0 ?x1) (when (del_inv_on ?x0 ?x1) (not (inv_on ?x0 ?x1)))) (forall (?x0 ?x1) (when (Ap_inv_on ?x0 ?x1) (not (Ap_inv_on ?x0 ?x1)))) (forall (?x0 ?x1) (when (Am_inv_on ?x0 ?x1) (not (Am_inv_on ?x0 ?x1)))) (forall (?x0) (when (ins_exists_on ?x0) (exists_on ?x0))) (forall (?x0) (when (del_exists_on ?x0) (not (exists_on ?x0)))) (forall (?x0) (when (Ap_exists_on ?x0) (not (Ap_exists_on ?x0)))) (forall (?x0) (when (Am_exists_on ?x0) (not (Am_exists_on ?x0)))) (forall (?x0) (when (ins_exists_inv_on ?x0) (exists_inv_on ?x0))) (forall (?x0) (when (del_exists_inv_on ?x0) (not (exists_inv_on ?x0)))) (forall (?x0) (when (Ap_exists_inv_on ?x0) (not (Ap_exists_inv_on ?x0)))) (forall (?x0) (when (Am_exists_inv_on ?x0) (not (Am_exists_inv_on ?x0)))) (forall (?x) (when (ins_block ?x) (block ?x))) (forall (?x) (when (del_block ?x) (not (block ?x)))) (forall (?x) (when (Ap_block ?x) (not (Ap_block ?x)))) (forall (?x) (when (Am_block ?x) (not (Am_block ?x)))) (forall (?x) (when (ins_blocked ?x) (blocked ?x))) (forall (?x) (when (del_blocked ?x) (not (blocked ?x)))) (forall (?x) (when (Ap_blocked ?x) (not (Ap_blocked ?x)))) (forall (?x) (when (Am_blocked ?x) (not (Am_blocked ?x))))))
)