(define (problem elevators_problem)
(:domain elevators)
(:init
       (origin pass_c a)
       (destin pass_c e)
       (origin pass_b a)
       (destin pass_b a)
       (next a d)
       (next d e)
       (liftat a))
(:goal (and (forall (?x - object) (or (served ?x) (not (DATALOG_PASSENGER ?x)))) (not (incompatible_update))))
)