(define (problem elevators_problem)
	(:domain elevators)
	(:objects pass_c pass_b a d e )
	(:init
		(origin pass_c a)
		(destin pass_c e)
		(origin pass_b a)
		(destin pass_b a)
		(next a d)
		(next d e)
		(lift_at a)
	)
	(:goal (not (exists (?x) 
 		 (and 
 			 (mko (passenger ?x)) 
 			 (not (mko (served ?x))) 
 		 )) 
 	 ))
)