import re

import pddl.datalog as datalog
import pddl.parser as pddl
from coherence_update.rules.symbols import (
    A_OR_AP_CL,
    ADEL,
    AP_CL,
    APLUS,
    COMPATIBLE_UPDATE,
    DEL,
    DEL_CL,
    INCOMPATIBLE_UPDATE,
    INS,
    INS_CL,
    MIN_X_IN_TAU,
    PRE_INS,
    UPDATING,
)

QUERY_PREDICATE_NAME = "QUERY"
_QUERY_NAME = re.compile(QUERY_PREDICATE_NAME + r"(\d+)")
INCONSISTENCY_PREDICATE_NAME = "inconsistent"


def is_primed_predicate_name(name):
    return name.startswith("DATALOG_")


def is_update_predicate_name(name):
    return name == UPDATING or name == INCOMPATIBLE_UPDATE or name == COMPATIBLE_UPDATE


def is_coherence_update_predicate_name(name):
    """True for the predicates generated by the coherence-update machinery.

    Every such predicate carries a prefix containing "_" (or is one of the
    fixed control predicates).  User names can never contain "_" (see
    normalize_user_name), so this test cannot misfire on a concept or role.

    The bare existsP / existsinvP concepts are deliberately *not* included:
    they are ordinary ABox predicates maintained by the update action.  Bare
    invP names only occur in rules that are never reachable.  Matching on the
    "exists"/"inv" prefixes used to misclassify user names such as "invoice".
    """
    return (
        name.startswith(INS)
        or name.startswith(DEL)
        or name.startswith(APLUS)
        or name.startswith(ADEL)
        or name.startswith(A_OR_AP_CL)
        or name.startswith(AP_CL)
        or name.startswith(DEL_CL)
        or name.startswith(MIN_X_IN_TAU)
        or name.startswith(PRE_INS)
        or name.startswith(INS_CL)
        or is_update_predicate_name(name)
    )


def is_non_horn_aux_predicate_name(name):
    name = name.lower()
    return name.startswith("nonhornaux") or name.startswith("_")


def prime_predicate_name(original):
    return "DATALOG_%s" % original.upper()


def unprime_predicate_name(primed_name):
    if primed_name.startswith("DATALOG_"):
        return primed_name[8:].lower()
    return primed_name


def query_predicate_name(idx):
    return QUERY_PREDICATE_NAME + str(idx)


def get_query_id(name):
    """Index i of a generated QUERY<i> name, or None for any other name.

    Clipper preserves the case of query heads, so the match is exact; a user
    concept such as "queryresult" is not a query (it used to crash int()).
    """
    match = _QUERY_NAME.fullmatch(name)
    return int(match.group(1)) if match else None


def get_parameter_list(length, var_name="?x%d"):
    if length == 0:
        return []
    else:
        return [pddl.TypedList([var_name % j for j in range(length)])]


def encodes_inconsistency(head):
    return isinstance(head, datalog.Falsity) or head.name == "nothing"
