NOT = "-"
RULE_SEPARATOR = " :- "
WORD_SEPARATOR = "_"

COMPATIBLE_UPDATE = "compatible" + WORD_SEPARATOR + "update"
INCOMPATIBLE_UPDATE = "incompatible" + WORD_SEPARATOR + "update"
ACTION_UPDATE_NAME = "update"
UPDATING = "updating"
INS = "ins" + WORD_SEPARATOR
DEL = "del" + WORD_SEPARATOR
REQUEST = WORD_SEPARATOR + "request"
CLOSURE = WORD_SEPARATOR + "closure"
END = ""

A_OR_AP_CL = "AOrApCl" + WORD_SEPARATOR
AP_CL = "ApCl" + WORD_SEPARATOR
DEL_CL = "DelCl" + WORD_SEPARATOR
MIN_X_IN_TAU = "Min" + WORD_SEPARATOR
PRE_INS = "PreInsCl" + WORD_SEPARATOR
INS_CL = "InsCl" + WORD_SEPARATOR
