(define (domain Test)
(:constants
  a - object)
(:predicates
  (preda ?x - object)
  (predb ?x - object)
  (predc ?x - object)
  (predd ?x - object)
  (AUX0)
  (AUX1 ?x0 - object)
  (AUX2 ?x - object)
  (AUX3 ?x - object))
(:derived (predd ?x0 - object)
          (and (preda ?x0) (AUX1 ?x0 - object)))
(:derived (AUX0)
          (forall (?x1 - object) (predc ?x1)))
(:derived (AUX1 ?x0 - object)
          (or (predb ?x0) (forall (?x1 - object) (predc ?x1))))
(:derived (AUX2 ?x - object)
          (or (predb ?x) (predc ?x)))
(:derived (AUX3 ?x - object)
          (and (preda ?x) (or (predb ?x) (predc ?x))))
(:action add
  :parameters (?x - object)
  :precondition (and (forall (?x1 - object) (predc ?x1)) (not (preda ?x)))
  :effect (and ))
)