(define (domain Test)
(:constants
  a - object)
(:predicates
  (preda ?x - object)
  (predb ?x - object)
  (predc ?x - object)
  (predd ?x - object)
  (AUX0 ?x0 - object)
  (AUX1)
  (AUX2 ?x - object)
  (AUX3 ?x - object))
(:derived (predd ?x0 - object)
          (and (AUX0 ?x0) (preda ?x0)))
(:derived (AUX0 ?x0 - object)
          (or (AUX1) (predb ?x0)))
(:derived (AUX1)
          (forall (?x1 - object) (predc ?x1)))
(:derived (AUX2 ?x - object)
          (and (AUX3 ?x) (preda ?x)))
(:derived (AUX3 ?x - object)
          (or (predb ?x) (predc ?x)))
(:action add
  :parameters (?x - object)
  :precondition (and (AUX1) (not (preda ?x)))
  :effect (when (exists (?x - object) (AUX2 ?x)) (and (preda ?x) (predb ?x))))
)