(define (domain Blocks)
(:constants
  A D B C - object)
(:predicates
  (onblock ?x ?y - object)
  (on ?x ?y - object)
  (block ?x - object)
  (blocked ?x - object)
  (updating)
  (incompatible_update)
  (ins_onblock ?x ?y - object)
  (del_onblock ?x ?y - object)
  (ins_onblock_request ?x ?y - object)
  (del_onblock_request ?x ?y - object)
  (ins_onblock_closure ?x ?y - object)
  (ins_on ?x ?y - object)
  (del_on ?x ?y - object)
  (ins_on_request ?x ?y - object)
  (del_on_request ?x ?y - object)
  (ins_on_closure ?x ?y - object)
  (ins_block ?x - object)
  (del_block ?x - object)
  (ins_block_request ?x - object)
  (del_block_request ?x - object)
  (ins_block_closure ?x - object)
  (ins_blocked ?x - object)
  (del_blocked ?x - object)
  (ins_blocked_request ?x - object)
  (del_blocked_request ?x - object)
  (ins_blocked_closure ?x - object)
  (DATALOG_BLOCK ?x0 - object)
  (DATALOG_ON ?x0 ?x1 - object)
  (DATALOG_BLOCKED ?x0 - object))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (del_block_request ?y0) (ins_block_request ?y0))))
(:derived (DATALOG_BLOCK ?x0 - object)
          (block ?x0))
(:derived (DATALOG_BLOCK ?x0 - object)
          (exists (?y0 - object) (onblock ?y0 ?x0)))
(:derived (del_on ?x0 ?x1 - object)
          (and (del_blocked_request ?x1) (on ?x0 ?x1)))
(:derived (updating )
          (exists (?y0 ?y1 - object) (ins_on_request ?y0 ?y1)))
(:derived (ins_block ?x0 - object)
          (ins_block_closure ?x0))
(:derived (updating )
          (exists (?y0 ?y1 - object) (del_onblock_request ?y0 ?y1)))
(:derived (DATALOG_ON ?x0 ?x1 - object)
          (on ?x0 ?x1))
(:derived (DATALOG_ON ?x0 ?x1 - object)
          (onblock ?x0 ?x1))
(:derived (ins_blocked ?x0 - object)
          (and (ins_blocked_request ?x0) (not (blocked ?x0))))
(:derived (DATALOG_BLOCKED ?x0 - object)
          (blocked ?x0))
(:derived (DATALOG_BLOCKED ?x0 - object)
          (exists (?y0 - object) (DATALOG_ON ?y0 ?x0)))
(:derived (updating )
          (exists (?y0 ?y1 - object) (del_on_request ?y0 ?y1)))
(:derived (del_onblock ?x0 ?x1 - object)
          (and (del_onblock_request ?x0 ?x1) (onblock ?x0 ?x1)))
(:derived (updating )
          (exists (?y0 - object) (ins_block_request ?y0)))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_on_request ?y0 ?y1) (ins_onblock_request ?y0 ?y1))))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_blocked_request ?y0) (ins_on_request ?y1 ?y0))))
(:derived (ins_onblock ?x0 ?x1 - object)
          (ins_onblock_closure ?x0 ?x1))
(:derived (del_block ?x0 - object)
          (and (block ?x0) (del_block_request ?x0)))
(:derived (del_onblock ?x0 ?x1 - object)
          (and (del_block_request ?x1) (onblock ?x0 ?x1)))
(:derived (incompatible_update )
          (exists (?y0 - object) (and (del_blocked_request ?y0) (ins_blocked_request ?y0))))
(:derived (ins_block_closure ?x0 - object)
          (exists (?y0 - object) (and (del_onblock ?y0 ?x0) (not (block ?x0)) (not (del_block_request ?x0)) (not (ins_block_request ?x0)))))
(:derived (ins_blocked ?x0 - object)
          (ins_blocked_closure ?x0))
(:derived (updating )
          (exists (?y0 - object) (del_block_request ?y0)))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_blocked_request ?y0) (ins_onblock_request ?y1 ?y0))))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_block_request ?y0) (ins_onblock_request ?y1 ?y0))))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_on_request ?y0 ?y1) (ins_on_request ?y0 ?y1))))
(:derived (del_blocked ?x0 - object)
          (and (blocked ?x0) (del_blocked_request ?x0)))
(:derived (updating )
          (exists (?y0 - object) (ins_blocked_request ?y0)))
(:derived (ins_on ?x0 ?x1 - object)
          (and (ins_on_request ?x0 ?x1) (not (on ?x0 ?x1))))
(:derived (ins_blocked_closure ?x0 - object)
          (exists (?y0 - object) (and (del_onblock ?y0 ?x0) (not (blocked ?x0)) (not (del_blocked_request ?x0)) (not (ins_blocked_request ?x0)))))
(:derived (ins_onblock ?x0 ?x1 - object)
          (and (ins_onblock_request ?x0 ?x1) (not (onblock ?x0 ?x1))))
(:derived (incompatible_update )
          (exists (?y0 ?y1 - object) (and (del_onblock_request ?y0 ?y1) (ins_onblock_request ?y0 ?y1))))
(:derived (del_onblock ?x0 ?x1 - object)
          (and (del_on_request ?x0 ?x1) (onblock ?x0 ?x1)))
(:derived (ins_blocked_closure ?x0 - object)
          (exists (?y0 - object) (and (del_on ?y0 ?x0) (not (blocked ?x0)) (not (del_blocked_request ?x0)) (not (ins_blocked_request ?x0)))))
(:derived (updating )
          (exists (?y0 ?y1 - object) (ins_onblock_request ?y0 ?y1)))
(:derived (ins_on ?x0 ?x1 - object)
          (ins_on_closure ?x0 ?x1))
(:derived (del_on ?x0 ?x1 - object)
          (and (del_on_request ?x0 ?x1) (on ?x0 ?x1)))
(:derived (ins_on_closure ?x0 ?x1 - object)
          (and (del_onblock ?x0 ?x1) (not (del_on_request ?x0 ?x1)) (not (ins_on_request ?x0 ?x1)) (not (on ?x0 ?x1))))
(:derived (ins_block ?x0 - object)
          (and (ins_block_request ?x0) (not (block ?x0))))
(:derived (updating )
          (exists (?y0 - object) (del_blocked_request ?y0)))
(:derived (del_onblock ?x0 ?x1 - object)
          (and (del_blocked_request ?x1) (onblock ?x0 ?x1)))
(:action move
  :parameters (?x ?y ?z - object)
  :precondition (and (DATALOG_ON ?x ?y) (not (DATALOG_BLOCKED ?x)) (not (DATALOG_BLOCKED ?z)) (not (updating)))
  :effect (and (del_on_request ?x ?y) (ins_onblock_request ?x ?z)))
(:action update
  :parameters ()
  :precondition (and (updating) (not (incompatible_update)))
  :effect (and (forall (?x ?y) (when (ins_onblock ?x ?y) (onblock ?x ?y))) (forall (?x ?y) (when (del_onblock ?x ?y) (not (onblock ?x ?y)))) (forall (?x ?y) (when (ins_onblock_request ?x ?y) (not (ins_onblock_request ?x ?y)))) (forall (?x ?y) (when (del_onblock_request ?x ?y) (not (del_onblock_request ?x ?y)))) (forall (?x ?y) (when (ins_on ?x ?y) (on ?x ?y))) (forall (?x ?y) (when (del_on ?x ?y) (not (on ?x ?y)))) (forall (?x ?y) (when (ins_on_request ?x ?y) (not (ins_on_request ?x ?y)))) (forall (?x ?y) (when (del_on_request ?x ?y) (not (del_on_request ?x ?y)))) (forall (?x) (when (ins_block ?x) (block ?x))) (forall (?x) (when (del_block ?x) (not (block ?x)))) (forall (?x) (when (ins_block_request ?x) (not (ins_block_request ?x)))) (forall (?x) (when (del_block_request ?x) (not (del_block_request ?x)))) (forall (?x) (when (ins_blocked ?x) (blocked ?x))) (forall (?x) (when (del_blocked ?x) (not (blocked ?x)))) (forall (?x) (when (ins_blocked_request ?x) (not (ins_blocked_request ?x)))) (forall (?x) (when (del_blocked_request ?x) (not (del_blocked_request ?x))))))
)